INTYGFV-15549: Refactored AESEncrypter.
sklintyg/rehabstod pull request #367
Opened 2023-05-08 11:10 UTC by ChrilleSigerhed

2023-05-08 11:13 UTC, mhornfeldt approved these changes

2023-05-08 12:58 UTC, mww-sopra-steria requested changes
A few comments that we discussed separately.

2023-05-08 12:58 UTC, mww-sopra-steria commented on web/src/test/java/se/inera/intyg/rehabstod/web/controller/api/SjukfallControllerTest.java
> +    private AESEncrypter aesEncrypter;
Add test for the encrypted and non-encrypted patientId

2023-05-08 12:58 UTC, mww-sopra-steria commented on web/src/main/java/se/inera/intyg/rehabstod/service/sjukfall/util/AESEncrypter.java
> +    public String encryptPatientId(String value) {
Maybe could refactor the class to reuse the cipher object. One for decrypt and one for encrypt. 

Also consider the name of the class to something more specific. 

Would be great to reintroduce some unit tests. You can use the @Value in the constructor and initialise it for test with different keys.

2023-05-09 07:04 UTC, mww-sopra-steria approved these changes
Looks good!

2023-05-09 07:20 UTC, merged